"""Initial tables

Revision ID: face9c8fd05d
Revises: 
Create Date: 2025-06-02 00:52:43.453745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'face9c8fd05d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_averages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('average_price', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_averages_id'), 'stock_averages', ['id'], unique=False)
    op.create_index(op.f('ix_stock_averages_ticker'), 'stock_averages', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_averages_ticker'), table_name='stock_averages')
    op.drop_index(op.f('ix_stock_averages_id'), table_name='stock_averages')
    op.drop_table('stock_averages')
    # ### end Alembic commands ###
